name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Narco

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: narco
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run backend tests
        run: ./mvnw test


  e2e:
    runs-on: ubuntu-latest
    needs: backend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: narco
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Angular dependencies
        working-directory: Angular_Narco
        run: npm ci

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Make mvnw executable
        working-directory: Narco
        run: chmod +x mvnw

      - name: Start backend
        working-directory: Narco
        run: |
          ./mvnw spring-boot:run &
          sleep 45

      - name: Start Angular
        working-directory: Angular_Narco
        run: |
          npm start &
          sleep 30

      - name: Run Selenium e2e tests
        working-directory: Angular_Narco
        run: npm run e2e